### ISSUE TITLE
Special Statgen request

### ISSUE THREAD

**Issue by Spaaaace** [lemtzas/Rollem#18]
Would like to be able to quickly generate stats for a custom system. 

Roll is 5 sets of |1d6-1d6| (Absolute value of the equation, so no negatives)
all 0s (matching numbers in a set) are rerolled until a non zero value is achieved
The total of all dice rolled is added at the end of the stat set.

In Example

2d6,2d6,2d6,2d6,2d6
[3 - 5] = 2, [4 - 4] = 0, [3 - 1] = 2, [1 - 6] = 5, [1 - 2] = 1

Reroll the second set due to a result of 0

2d6
[2 - 4] = 2

Producing the array

[2,2,2,5,1]

and then adding the total of all rolls to the end of the array, producing the final result.

[2,2,2,5,1] 36

**Comment by lemtzas** [comment]
It is done.

``` irc
<Lemtzas> !spacegen verbose
<Rollem> Lemtzas requested some stats:
<Rollem> Lemtzas, | 5 - 4 | r1 => 1
<Rollem> Lemtzas, | 3 - 2 |    => 1
<Rollem> Lemtzas, | 6 - 5 |    => 1
<Rollem> Lemtzas, | 1 - 4 |    => 3
<Rollem> Lemtzas, | 1 - 3 |    => 2
<Rollem> Lemtzas, [3, 2, 1, 1, 1]
<Lemtzas> !spacegen
<Rollem> Lemtzas, [5, 3, 1, 1, 1]
```
